# Generated by Django 4.2 on 2024-09-01 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='updates_at',
            new_name='updated_at',
        ),
    ]
